// Game thumbnail mapping - uses game names to create themed visual cards
const gameImages = {
    // Popular/Featured with custom styling
    'cookie-clicker': { emoji: '🍪', color: '#D4A574' },
    '2048': { emoji: '2️⃣', color: '#EAE8D9' },
    'flappy-bird': { emoji: '🐦', color: '#70C1B3' },
    'chrome-dino': { emoji: '🦖', color: '#4A4A4A' },
    'subway-surfers': { emoji: '🚇', color: '#1A1A2E' },
    'geometry-dash-lite': { emoji: '📐', color: '#FF006E' },
    'slope': { emoji: '⛷️', color: '#00D9FF' },
    'drift-boss': { emoji: '🏎️', color: '#FF4500' },
    'fireboy-and-watergirl': { emoji: '🔥', color: '#FF5722' },
    'run-3': { emoji: '🏃', color: '#3498DB' },
    'temple-run-2': { emoji: '🏛️', color: '#8B4513' },
    'doodle-jump': { emoji: '📝', color: '#FFD700' },
    'cut-the-rope': { emoji: '✂️', color: '#FF69B4' },
    'basketball-stars': { emoji: '🏀', color: '#FF8C00' },
    'retro-bowl': { emoji: '🏈', color: '#8B0000' },
    'clicker-heroes': { emoji: '⚔️', color: '#654321' },
    '1v1-lol': { emoji: '🎮', color: '#1E90FF' },
    'friday-night-funkin': { emoji: '🎤', color: '#FF1493' },
    'awesome-tanks': { emoji: '🎯', color: '#228B22' },
    'fnaf-2': { emoji: '🤖', color: '#8B0000' },
    
    // Action Games
    'motox3m': { emoji: '🏍️', color: '#FF6B00' },
    'drive-mad': { emoji: '🚗', color: '#DC143C' },
    'eggy-car': { emoji: '🥚', color: '#FFD700' },
    'rocket-league-2d': { emoji: '⚽', color: '#0079B5' },
    'stickman-hook': { emoji: '🎣', color: '#8B4513' },
    'tunnel-rush': { emoji: '🌀', color: '#00CED1' },
    'rooftop-snipers': { emoji: '🎯', color: '#2F4F4F' },
    'getaway-shootout': { emoji: '🔫', color: '#696969' },
    'time-shooter': { emoji: '⏰', color: '#FF69B4' },
    'pull-of-war': { emoji: '🎪', color: '#FF8C00' },
    'x-trench-run': { emoji: '✈️', color: '#4169E1' },
    '10-minutes-till-dawn': { emoji: '🌙', color: '#191970' },
    'shadow-fight': { emoji: '🥋', color: '#1C1C1C' },
    'boxing-random': { emoji: '🥊', color: '#A9A9A9' },
    'volleyball-random': { emoji: '🏐', color: '#FFD700' },
    'soccer-random': { emoji: '⚽', color: '#000000' },
    'basket-random': { emoji: '🏀', color: '#FF8C00' },
    
    // Puzzle Games
    'vex-3': { emoji: '❌', color: '#FF6347' },
    'vex-4': { emoji: '❌', color: '#FF6347' },
    'vex-5': { emoji: '❌', color: '#FF6347' },
    'vex-6': { emoji: '❌', color: '#FF6347' },
    'vex-7': { emoji: '❌', color: '#FF6347' },
    'tic-tac-what': { emoji: '⭕', color: '#0000CD' },
    'hextris': { emoji: '⬡', color: '#FF1493' },
    'three-ball-3d': { emoji: '🔮', color: '#FF69B4' },
    'restless-wing-syndrome': { emoji: '🪶', color: '#FFB6C1' },
    'reach-the-core': { emoji: '⬇️', color: '#FF4500' },
    'where-is-the-water': { emoji: '💧', color: '#00BFFF' },
    'debris': { emoji: '⚛️', color: '#808080' },
    
    // Idle Games
    'particle-clicker': { emoji: '⚛️', color: '#009ACD' },
    'incremancer': { emoji: '📊', color: '#7851A9' },
    'progress-knight-quest': { emoji: '⚔️', color: '#FFD700' },
    'progress-knight-reborn': { emoji: '👑', color: '#FFD700' },
    'breaklock': { emoji: '🔓', color: '#DC143C' },
    'idle-breakout': { emoji: '🧱', color: '#FF8C00' },
    'monkey-mart': { emoji: '🎪', color: '#FF6347' },
    'tiny-fishing': { emoji: '🎣', color: '#4682B4' },
    'the-final-earth': { emoji: '🌍', color: '#2E8B57' },
    'aground': { emoji: '⛏️', color: '#8B4513' },
    'planet-life': { emoji: '🪐', color: '#4169E1' },
    
    // Adventure/Story Games
    'there-is-no-game': { emoji: '🎮', color: '#FF69B4' },
    'a-dark-room': { emoji: '🕯️', color: '#2F4F4F' },
    'abandoned': { emoji: '👻', color: '#696969' },
    'abandoned-2': { emoji: '👻', color: '#696969' },
    'the-treasure': { emoji: '💎', color: '#FFD700' },
    'another-gentlemans-adventure': { emoji: '🧳', color: '#8B4513' },
    'dune': { emoji: '🪜', color: '#D2B48C' },
    'ages-of-conflict': { emoji: '⚔️', color: '#8B0000' },
    'lion-soldiers-vengeance': { emoji: '🦁', color: '#FFD700' },
    'crossy-road': { emoji: '🚶', color: '#FF6347' },
    
    // Music/Rhythm Games
    'web-osu': { emoji: '🎵', color: '#FF69B4' },
    'trace': { emoji: '🎼', color: '#1E90FF' },
    
    // Strategy/Tactical
    'core-ball': { emoji: '⚪', color: '#FFFFFF' },
    'amidst-the-sky': { emoji: '☁️', color: '#87CEEB' },
    'brawl-stars-project-laser': { emoji: '⭐', color: '#FFD700' },
    'bit-life': { emoji: '👶', color: '#87CEEB' },
    'smart-ball': { emoji: '🔴', color: '#FF0000' },
    'sabercut': { emoji: '⚡', color: '#FFD700' },
    
    // Misc/Unique
    'conways-game-of-life': { emoji: '🧬', color: '#00FF00' },
    'sandspiel': { emoji: '🪢', color: '#D2B48C' },
    'scuba-bear': { emoji: '🧑‍🤿', color: '#00BFFF' },
    'yohoho': { emoji: '🏴‍☠️', color: '#000000' },
    'smash-karts': { emoji: '🏎️', color: '#FF6347' },
    'station-saturn': { emoji: '🪐', color: '#8B4513' },
    'gunspin': { emoji: '🔫', color: '#696969' },
    'doge-miner': { emoji: '🐕', color: '#FFD700' },
    'n-step-steve-part-1': { emoji: '👨', color: '#8B4513' },
    'n-step-steve-part-2': { emoji: '👨', color: '#8B4513' },
    'n-gon': { emoji: '🔶', color: '#FF8C00' },
    'gons-io': { emoji: '🌐', color: '#00CED1' },
    'evowars': { emoji: '🦾', color: '#FF6347' },
    'ampler-launcher': { emoji: '🚀', color: '#FF4500' },
    'rookie-bowman': { emoji: '🏹', color: '#8B4513' },
    'pcraft': { emoji: '⛓️', color: '#696969' },
    'ovo': { emoji: '🥚', color: '#FFD700' },
    'slice-master': { emoji: '🔪', color: '#C0C0C0' },
    'family-feud': { emoji: '👨‍👩‍👧', color: '#FFD700' },
    'duck-life-4': { emoji: '🦆', color: '#FFD700' },
    'tanuki-sunset': { emoji: '🦝', color: '#FF8C00' },
    'two-ball-3d': { emoji: '🟣', color: '#9932CC' },
    'geometry-vibes': { emoji: '📐', color: '#FF69B4' },
    'geometry-vibes-monster': { emoji: '👹', color: '#FF1493' },
    'geometry-vibes-x-ball': { emoji: '⚪', color: '#00FF00' },
    'rift-shift': { emoji: '🌌', color: '#4B0082' },
    'maptroid': { emoji: '🗺️', color: '#FF8C00' },
    'mario-game': { emoji: '🍄', color: '#FF0000' },
    'fireboy-and-watergirl-2': { emoji: '🔥', color: '#FF5722' },
    'fireboy-and-watergirl-3': { emoji: '🔥', color: '#FF5722' },
    'fireboy-and-watergirl-4': { emoji: '🔥', color: '#FF5722' },
    'five-nights-at-epsteins': { emoji: '🌙', color: '#2F4F4F' },
    'awesome-tanks-2': { emoji: '🎯', color: '#228B22' },
    'babel-tower': { emoji: '🏙️', color: '#696969' },
    'drive-mad-s': { emoji: '🏎️', color: '#FF6347' },
    'geometry-dash-remastered': { emoji: '📐', color: '#FF006E' },
    'volley-random': { emoji: '🏐', color: '#FFD700' },
    'clicker-heroes-updated': { emoji: '⚔️', color: '#654321' },
    'retro-bowl-old': { emoji: '🏈', color: '#8B0000' },
    'run-3-beta': { emoji: '🏃', color: '#3498DB' },
    'subway-surfers-ny': { emoji: '🗽', color: '#1A1A2E' },
    'flash': { emoji: '⚡', color: '#FFD700' }
};

function getGameImage(gameName) {
    return gameImages[gameName] || { emoji: '🎮', color: '#00f0ff' };
}
